pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "your_dockerhub_username/my-app"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Manojgit45/Devops-project.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE app/'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
        stage('Deploy with Terraform') {
            steps {
                script {
                    sh '''
                    cd terraform
                    terraform init
                    terraform apply -auto-approve -var="docker_image=$DOCKER_IMAGE"
                    '''
                }
            }
        }
        stage('Deploy with Ansible') {
            steps {
                script {
                    sh '''
                    cd ansible
                    ansible-playbook -i inventory playbook.yml --extra-vars "docker_image=$DOCKER_IMAGE"
                    '''
                }
            }
        }
    }
}

